name: Build libwebp for Android (arm64-v8a)

on:
  push:
    paths:
      - libwebp/**
      - .github/workflows/build_libwebp.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r10e
      - name: Build libpng for Android
        run: |
          cd libwebp
          ./build.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./libwebp/obj/local/**/*
          name: build
