name: Build libpng for Android (arm64-v8a)

on:
  push:
    paths:
      - libpng/**
      - .github/workflows/build_libpng.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
      - name: Build libpng for Android
        run: |
          cd libpng
          ./build_test.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./libpng/obj/**/*
          name: build
